Ready for code review
Rudey-ua/prestashop_plugin pull request #1
Opened 2022-08-23 11:06 UTC by Rudey-ua

2022-08-23 18:30 UTC, Rudey-ua commented on classes/Client.php
> +<?php
Ok

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft requested changes
1. Add namespaces to each class and require classes using `use`.
2. Var naming is important thing, it could make code more readable.
3. Investigate: early-return pattern, PSR-12 code standard, ternary operator and try to find ways to code without line duplications (DRY principal).
4. Add /vendor to .gitignore  

Conclusion: looks good, but we could improve some moments!

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +        }
1. elseif is unnecessary cause in case when $orderStatus == 'compted' - the user will be redirected and next code lines won't be executed
2. Investigate what Is early-return pattern and use it here

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +            $customer_id = $_GET['id_customer'];
I think this vars not really necessary, cause they are used only one time

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +            $order->setCurrentState(2); // Completed
Comment is really helpful, but we could provide solution even better, for example we could create Helper class and move there const with status-mapping, and it could look:  `$order->setCurrentState(Helper::STATUSES['completed'])`

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +            $order->setCurrentState(8); // Error
The same

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +            $order->setCurrentState(8); // Error
Line duplications, I wonder how we could decrease them?

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/webhook.php
> +        ];
We could create Helper class and move it there, but if you have even better way - lets discuss

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +        $message = '';
remove this var init

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +            'message' => $message,
Probably we could use` 'message' => $message ?? ''`, but we have to test it.

Also take a look at this article - https://php720.com/lesson/19

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +        $API_KEY = Configuration::get('API_KEY');
use snake_case here

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +            }
1. why we have two names for cert value: Tools::getValue('certificate') and Tools::getValue('cert')?
2. Try not to use if statements here, this article could be helpful - https://php720.com/lesson/19

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +        $banks = $client->createClient()->getIdealIssuers();
Actually not $banks, but $idealIssuers

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on translations/de.php
> +$_MODULE['<{mymodule}prestashop>mymodule_2ddddc2a736e4128ce1cdfd22b041e7f'] = 'Mein Modul';
Add other translations

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on translations/nl.php
> +$_MODULE['<{mymodule}prestashop>mymodule_2ddddc2a736e4128ce1cdfd22b041e7f'] = 'Mijn module';
Add other translations

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on views/templates/hook/payment_options.tpl
> +        {foreach from=$banks item=bank}
use translations here

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on views/templates/hook/payment_return.tpl
> +    <a href="http://localhost/%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7">Go to checkout page</a>
Use translations

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on views/templates/hook/payment_return.tpl
> +    <a href="http://localhost/%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7">Go to checkout page</a>
Localization*

2022-08-24 10:32 UTC, Denis-Tsyganok-Leasoft commented on views/templates/admin/configuration.tpl
> +                Want to use a caCert?
Use Localization here (lang translations)

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft requested changes

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +        $client = $client->createClient();
probably we could move 'createClient' logic to __consturct func, and use it like `$client = new ClientBuilder();`, but currently it's not necessary

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/validation.php
> +        $order_status = $gingerOrder['status'];
I see two different code styles $gingerOrder and $purchase_id, decide which code style to use: camelCase or snake_case.

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/webhook.php
> +            $client = $client->createClient();
$client = (new ClientBuilder())->createClient();

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/payment.php
> +
$client = (new ClientBuilder())->createClient();

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on controllers/front/payment.php
> +
$merchant_order - looks like this a ginger order

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on mymodule.php
> +        $idealIssuers = $client->createClient()->getIdealIssuers();
$client = (new ClientBuilder())->createClient()

2022-08-31 06:16 UTC, Denis-Tsyganok-Leasoft commented on classes/OrderBuilder.php
> +        return 'http://localhost/module/mymodule/validation?id_cart=' . $this->getCart()->id . '&id_module=' . $this->getModule()->id . '&id_customer=' . $this->getCustomer()->secure_key;
Plugin doesn't work in a server cause here is hard-coded 'localhost', customer will be returned to the localhost, use context->link->getmodulelink() to create a return url

2022-08-31 07:40 UTC, Denis-Tsyganok-Leasoft approved these changes

2022-08-31 08:59 UTC, merged